# Generated by Django 3.0.4 on 2020-03-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0002_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='product',
            new_name='csmodel',
        ),
    ]
