# Generated by Django 3.0.4 on 2020-03-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0006_developermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='developermodel',
            name='contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='developermodel',
            name='gmail',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
