# Generated by Django 3.0.4 on 2020-03-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0007_auto_20200328_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developermodel',
            name='contact',
            field=models.IntegerField(max_length=10),
        ),
    ]
