# Generated by Django 3.0.4 on 2020-03-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0009_auto_20200328_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developermodel',
            name='contact',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
