# Generated by Django 3.0.4 on 2020-03-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0012_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
