# Generated by Django 3.0.4 on 2020-03-29 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0013_cartmodel_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='Username',
            new_name='username',
        ),
    ]
