# Generated by Django 3.0.4 on 2020-03-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0015_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='state',
        ),
    ]
