# Generated by Django 3.0.4 on 2020-03-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0016_auto_20200329_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='productname',
            new_name='address1',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='img',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='price',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='username',
        ),
    ]
