# Generated by Django 3.0.4 on 2020-03-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0017_auto_20200329_2114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buyer',
        ),
    ]
