# Generated by Django 3.0.4 on 2020-03-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0018_delete_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
