# Generated by Django 3.0.4 on 2020-03-30 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0020_auto_20200330_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buyer',
        ),
    ]
