# Generated by Django 3.0.4 on 2020-03-30 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0022_buyer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buyer',
        ),
    ]
