# Generated by Django 3.0.4 on 2020-03-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0024_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='csmodel',
            name='category',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
