# Generated by Django 3.0.4 on 2020-03-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0026_auto_20200330_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='pcategory',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='pcategory',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
