# Generated by Django 3.0.4 on 2020-03-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0028_remodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('pid', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('uid', models.IntegerField()),
                ('title', models.TextField()),
                ('review', models.TextField()),
                ('star', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='remodel',
        ),
    ]
