# Generated by Django 3.0.4 on 2020-05-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0036_profiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profiles',
        ),
    ]
