# Generated by Django 3.0.4 on 2020-05-04 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0040_auto_20200504_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othermodel',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='othermodel',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='othermodel',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='othermodel',
            name='img4',
        ),
    ]
