# Generated by Django 3.0.4 on 2020-05-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0041_auto_20200504_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='othermodel',
            name='img1',
            field=models.ImageField(default=False, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='othermodel',
            name='img2',
            field=models.ImageField(default=True, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='othermodel',
            name='img3',
            field=models.ImageField(default=True, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='othermodel',
            name='img4',
            field=models.ImageField(default=True, upload_to='pics'),
            preserve_default=False,
        ),
    ]
