# Generated by Django 3.0.4 on 2020-05-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0044_auto_20200504_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='othermodel',
            name='img5',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='othermodel',
            name='img2',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='othermodel',
            name='img3',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='othermodel',
            name='img4',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
