# Generated by Django 3.0.4 on 2020-05-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0045_auto_20200504_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othermodel',
            name='img2',
            field=models.ImageField(blank=True, default="os.path.join(BASE_DIR,'static/img/transprent.png')", upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='othermodel',
            name='img3',
            field=models.ImageField(blank=True, default='', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='othermodel',
            name='img4',
            field=models.ImageField(blank=True, default='', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='othermodel',
            name='img5',
            field=models.ImageField(blank=True, default='', upload_to='pics'),
        ),
    ]
