# Generated by Django 3.0.4 on 2020-05-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0046_auto_20200505_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othermodel',
            name='img2',
            field=models.ImageField(blank=True, default='D:\\Workspace\\Projects\\xcellenceprojectgallery_Django\\static/img/xpg_banner1.png', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='othermodel',
            name='img3',
            field=models.ImageField(blank=True, default='D:\\Workspace\\Projects\\xcellenceprojectgallery_Django\\static/img/xpg_banner1.png', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='othermodel',
            name='img4',
            field=models.ImageField(blank=True, default='D:\\Workspace\\Projects\\xcellenceprojectgallery_Django\\static/img/xpg_banner1.png', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='othermodel',
            name='img5',
            field=models.ImageField(blank=True, default='D:\\Workspace\\Projects\\xcellenceprojectgallery_Django\\static/img/xpg_banner1.png', upload_to='pics'),
        ),
    ]
