# Generated by Django 3.0.4 on 2020-05-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0048_auto_20200505_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='latitude_Longitude',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
