# Generated by Django 3.0.4 on 2020-05-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpg', '0049_buyer_latitude_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='latitude_Longitude',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='buyer',
            name='longitude',
            field=models.CharField(default=False, max_length=100),
            preserve_default=False,
        ),
    ]
